export const t = (lang) => {
    if (lang == 'ru') {
        return {
            ImVPN: "привет! я vpn spydog",
            Imake: "Я делаю Интернет",
            limitless: "безлимитным и высокоскоростным",
            anonymous: "анонимность",
            hideyourip: "замени свой IP",
            beanonymous: "будь анонимным в сети интерне",
            fast: "высокая скорость",
            ourservershave: "получи доступ к",
            highspeed: "высокоскоростным серверам",
            largenumber: "большой выбор стран",
            weoffer: "мы предлагаем большой выбор серверов",
            differentcountries: "в разных странах",
            secure: "безопасность",
            Transfer: "передача трафика по",
            anencryptedtunnel: "зашифрованному каналу",
            next: "далее",
            skip: "пропустить",
            hideyouip: "смени свой ір Анонимный серфинг скорость",
            upto: "пропускная способность до 1000 мб, С",
            removeads: "БЕЗ РЕКЛАМЫ",
            havefun: "НАСЛАЖДАЙТЕСЬ АНОНИМНЫМ СЕРФИНГОМ БЕЗ РЕКЛАМЫ БЕЗОПАСНОСТЬ",
            Transfer2: "ПЕРЕДАЧА ТРАФИКА ПО ЗАШИФРОВАННОМУ КАНАЛУ",
            day3: "3 ДНЯ СОВЕРШЕННО БЕСПЛАТНО",
            cancelanytime: "отмена оплаты в любое время",
            afterwards: "далее 599р мес",
            tryforfree: "БЕСПЛАТНО",
            continuewithoutsubscription: "ПРОДОЛЖИТЬ БЕСПЛАТНО",
            restorepurchase: "ВОССТАНОВИТЬ ОПЛАТУ",
            Whysubscribe: "зачем нужна подписка",
            PrivacyPolicy: "политика конфиденциальности",
            Termsofuse: "пользовательское соглашение",
            AboutUs: "О Нас",
            Gopremium: "перейти на премиум",
            S3day: "3 ДНЯ СОВЕРШЕННО БЕСПЛАТНО Потом 2.99 мес- $",
            Premium: "Премиум Подписка",
            Language: "Язык",
            MainMenu: "меню",
            share: 'Поделиться',
            Disconect: 'Отключить',
            Connected: 'Соединять'
        }
    }
    else {
        return {
            ImVPN: "Hello! I'm VPN SpyDog",
            Imake: "I make the internet",
            limitless: "limitless at high speed",
            anonymous: "Anonymous",
            hideyourip: "Hide your IP",
            beanonymous: "Be anonymous on the internet",
            fast: "Fast",
            ourservershave: "Our servers have",
            highspeed: "high-speed",
            largenumber: "Large number of countries",
            weoffer: "We offer a large selection of servers",
            differentcountries: "different countries",
            secure: "Secure",
            Transfer: "Transfer traffic via",
            anencryptedtunnel: "an encrypted tunnel",
            next: "Next",
            skip: "Skip",
            hideyouip: "Hide your IP. Anonymous surfing",
            upto: "Up to 1000Mb/s bandwidth to explore",
            removeads: "Remove Ads",
            havefun: "Have fun",
            Transfer2: "Transfer traffic via encrypted tunnel",
            day3: "3-day free trial. No payment required.",
            cancelanytime: "Cancel anytime",
            afterwards: "Afterwards, 7.49$ / month",
            tryforfree: "Try for free",
            continuewithoutsubscription: "Continue without subscription",
            restorepurchase: "Restore purchase",
            Whysubscribe: "Why subscribe",
            PrivacyPolicy: "Privacy Policy",
            Termsofuse: "Terms of use",
            AboutUs: "About Us",
            Gopremium: "Go premium",
            S3day: "S3-day free trial. Then 2.99$ / month",
            Premium: "Premium features",
            Language: "Language",
            MainMenu: "Main Menu",
            share: 'Share',
            Disconect: 'Disconnected',
            Connected: 'Connected'
        }
    }
}